### ISSUE TITLE
What does Add dynamic shortcut do?

### ISSUE THREAD

**Issue by PanicPug** [tkuenneth/BeNice#18]
I can't find any information as to what Add dynamic shortcut does when creating a new app pair. I read through the Play Store site, on the website [https://www.thomaskuenneth.de/benice/](url) as well as here on GitHub, but couldn't find a thing about it.

**Comment by tkuenneth** [comment]
Here's a Google document describing different shortcut types: https://developer.android.com/develop/ui/views/launch/shortcuts/creating-shortcuts

I added dynamic shortxuts because a few users asked me if I could make the shortcuts available to other apps. Apps can query dynamic shortcuts and show them.
